### ISSUE TITLE
Force close Android 11

### ISSUE THREAD

**Issue by VasyaHH** [reiryuki/Extreme-Battery-Saver-Magisk-Module#4]
Hello. Extreme battery saver force close when I try to run it. No notification when default battery saver is active.
In logcat a see this error:
```
FATAL EXCEPTION: main
Process: com.google.android.flipendo, PID: 14708
java.lang.NoSuchFieldError: No instance field fontWeightAdjustment of type I in class Landroid/content/res/Configuration; or its superclasses (declaration of 'android.content.res.Configuration' appears in /system/framework/framework.jar)
	at com.google.android.material.resources.TypefaceUtils.maybeCopyWithFontWeightAdjustment(TypefaceUtils.java:52)
	at com.google.android.material.internal.CollapsingTextHelper.setExpandedTypefaceInternal(CollapsingTextHelper.java:499)
	at com.google.android.material.internal.CollapsingTextHelper.setExpandedTypeface(CollapsingTextHelper.java:457)
	at com.google.android.material.internal.CollapsingTextHelper$2.apply(CollapsingTextHelper.java:441)
	at com.google.android.material.resources.CancelableFontCallback.updateIfNotCancelled(CancelableFontCallback.java:69)
	at com.google.android.material.resources.CancelableFontCallback.onFontRetrievalFailed(CancelableFontCallback.java:54)
	at com.google.android.material.resources.TextAppearance$1.onFontRetrievalFailed(TextAppearance.java:205)
	at androidx.core.content.res.ResourcesCompat$FontCallback.lambda$callbackFailAsync$1(ResourcesCompat.java:490)
	at androidx.core.content.res.ResourcesCompat$FontCallback.$r8$lambda$3yv7dDJDSSH8XKTxkNkwYH6nK6w(Unknown Source:0)
	at androidx.core.content.res.ResourcesCompat$FontCallback$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by reiryuki** [comment]
Try this: https://t.me/androidryukimodsdiscussions/178103
Send full logcat after, even if it's working

This issue will be closed if no answer in 24 hours
