### ISSUE TITLE
App crahes on selecting "when to use" option

### ISSUE THREAD

**Issue by livcl-be** [reiryuki/Extreme-Battery-Saver-Magisk-Module#6]
The app crahes when i select the "when to use option". I am using a mi 9t with crdroid and microg (no gapps).

```
time: 1696367089833
msg: java.lang.SecurityException: Unable to start activity ComponentInfo{com.google.android.flipendo/com.google.android.flipendo.settings.SavingsModePreferenceActivity}: java.lang.SecurityException: 
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.flipendo/com.google.android.flipendo.settings.SavingsModePreferenceActivity}: java.lang.SecurityException: 
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3791)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7930)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: java.lang.SecurityException: 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3028)
	at android.os.Parcel.createException(Parcel.java:3012)
	at android.os.Parcel.readException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2937)
	at android.os.IServiceManager$Stub$Proxy.isDeclared(IServiceManager.java:520)
	at android.os.ServiceManagerProxy.isDeclared(ServiceManagerNative.java:90)
	at android.os.ServiceManager.isDeclared(ServiceManager.java:247)
	at android.os.ServiceManager.waitForDeclaredService(ServiceManager.java:297)
	at com.google.android.flipendo.PixelPowerHalExtManager.connectPowerExtService(PixelPowerHalExtManager.java:81)
	at com.google.android.flipendo.PixelPowerHalExtManager.<init>(PixelPowerHalExtManager.java:57)
	at com.google.android.flipendo.PixelPowerHalExtManager.getInstance(PixelPowerHalExtManager.java:48)
	at com.google.android.flipendo.BatterySaverManager.<init>(BatterySaverManager.java:98)
	at com.google.android.flipendo.BatterySaverManager.getInstance(BatterySaverManager.java:86)
	at com.google.android.flipendo.settings.SavingsModeSettingsPreferenceFragment.onCreatePreferences(SavingsModeSettingsPreferenceFragment.java:55)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2947)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:455)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:255)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1797)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1715)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1627)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
	at com.google.android.flipendo.settings.SavingsModePreferenceActivity.onCreate(SavingsModePreferenceActivity.java:39)
	at android.app.Activity.performCreate(Activity.java:8360)
	at android.app.Activity.performCreate(Activity.java:8339)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
	... 12 more

```

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 5 stuffs:

1) Explanations ✓
2) Magisk/KernelSU install log if it's a Magisk module #magisk_install_log
3) Disable any other else modules (except the module you want to report, AML, dirac misoundfx Remover, AOSP soundfx Remover, & Sound Alive FX Remover Magisk Module. But if you are reporting for AML Ryuki Mod, then you need to enable all audio mod module you have.)
4) Full logcat #logcat
5) Z folder #zfolder

If you miss one of them, read #bug_report again https://t.me/androidryukimodsdiscussions/2618 please! If you got boot-loop, read #workarounds! If you don't understand, learning is the best you can do. Thank you.
