### ISSUE TITLE
Android 11 force close

### ISSUE THREAD

**Issue by EtiLB7** [reiryuki/Extreme-Battery-Saver-Magisk-Module#7]
When i try to run the app, it force closes. The notification also doesn't show up. Here's the logcat:

FATAL EXCEPTION: main
Process: com.google.android.flipendo, PID: 5793
java.lang.NoSuchFieldError: No static field ACTION_DRAG_START of type Landroid/view/accessibility/AccessibilityNodeInfo$AccessibilityAction; in class Landroid/view/accessibility/AccessibilityNodeInfo$AccessibilityAction; or its superclasses (declaration of 'android.view.accessibility.AccessibilityNodeInfo$AccessibilityAction' appears in /system/framework/framework.jar!classes3.dex)
	at androidx.core.view.accessibility.AccessibilityNodeInfoCompat$AccessibilityActionCompat.<clinit>(AccessibilityNodeInfoCompat.java:608)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.updateAccessibilityActions(AppBarLayout.java:1728)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1722)
	at com.google.android.material.appbar.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:1321)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1340)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:953)
	at android.view.View.layout(View.java:22851)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22851)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22851)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
	at android.view.View.layout(View.java:22851)
	at android.view.ViewGroup.layout(ViewGroup.java:6389)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3475)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2943)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8181)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 5 stuffs:

1) Explanations ✓
2) Magisk/KernelSU install log if it's a Magisk module #magisk_install_log
3) Disable any other else modules (except the module you want to report, AML, dirac misoundfx Remover, AOSP soundfx Remover, & Sound Alive FX Remover Magisk Module. But if you are reporting for AML Ryuki Mod, then you need to enable all audio mod module you have.)
4) Full logcat #logcat
5) Z folder #zfolder

If you miss one of them, read #bug_report again https://t.me/androidryukimodsdiscussions/2618 please! If you got boot-loop, read #workarounds! If you don't understand, learning is the best you can do. Thank you.
